route:
    # repeat_interval: 30m
    # group_interval: 30m
    receiver: 'rocketchat'
    # receiver: 'slack'

receivers:
    - name: 'rocketchat'
      webhook_configs:
          - send_resolved: false
            url: '${WEBHOOK_URL}'

    # - name: 'slack'
    #   slack_configs:
    #       - send_resolved: true
    #         text: "{{ .CommonAnnotations.description }}"
    #         username: 'Prometheus'
    #         channel: '#<channel>'
    #         api_url: 'https://hooks.slack.com/services/T011UM3R8BT/<webhook-id>'
